apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "k8s-test-app"
  namespace: "testing"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "k8s-test-app"
  namespace: "testing"
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "k8s-test-app"
  namespace: "testing"
subjects:
  - kind: "ServiceAccount"
    name: "k8s-test-app"
    namespace: "testing"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "k8s-test-app"

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "k8s-test-app"
  namespace: "testing"
spec:
  selector:
    app.kubernetes.io/name: "k8s-test-app"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8080
      targetPort: 8080

---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "k8s-test-app"
  namespace: "testing"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "k8s-test-app"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "k8s-test-app"
    spec:
      containers:
        - name: "testing"
          image: "shadowuser17/testing:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8080
          resources:
            requests:
              cpu: "30m"
              memory: "20Mi"
            limits:
              cpu: "30m"
              memory: "35Mi"
