apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "k8s-runner"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "k8s-runner"
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "k8s-runner"
subjects:
  - kind: "User"
    name: "k8s-runner"
    apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: "Role"
  name: "k8s-runner"
  apiGroup: "rbac.authorization.k8s.io"

---
apiVersion: "actions.summerwind.dev/v1alpha1"
kind: "RunnerDeployment"
metadata:
  name: "k8s-runner"
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: "k8s-runner"
      repository: "ShadowUser17/k8s-test-app"
      labels:
        - "testing"
        - "k8s"
