apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "k8s-runner"
  namespace: "testing"

---
apiVersion: "actions.summerwind.dev/v1alpha1"
kind: "RunnerDeployment"
metadata:
  name: "k8s-runner"
  namespace: "testing"
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: "k8s-runner"
      repository: "ShadowUser17/k8s-test-app"
      labels:
        - "testing"
        - "k8s"
