apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "k8s-test-app"
  namespace: "k8s-test-app"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "k8s-test-app"
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "k8s-test-app"
subjects:
  - kind: "ServiceAccount"
    name: "k8s-test-app"
    namespace: "k8s-test-app"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "k8s-test-app"
