apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "k8s-test-app"
  namespace: "k8s-test-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "k8s-test-app"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "k8s-test-app"
    spec:
      serviceAccountName: "k8s-test-app"
      containers:
        - name: "testing"
          image: "shadowuser17/testing:latest"
          imagePullPolicy: "Always"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 8080
          resources:
            requests:
              cpu: "30m"
              memory: "20Mi"
            limits:
              cpu: "30m"
              memory: "35Mi"
