apiVersion: "v1"
kind: "Service"
metadata:
  name: "k8s-test-app"
  namespace: "k8s-test-app"
spec:
  selector:
    app.kubernetes.io/name: "k8s-test-app"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
