name: "Build docker image"
run-name: "${{ github.actor }}"
permissions: {}

on:
  push:
    branches:
      - "master"

jobs:
  build_app:
    runs-on: "testing"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Log in to Docker Hub"
        run: |
          docker login -u "${{ secrets.DOCKERHUB_LOGIN }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build Docker image"
        run: |
          docker build -t "shadowuser17/testing" .

      - name: "Push Docker image"
        run: |
          docker push "shadowuser17/testing"
