name: "Build application"
run-name: "${{ github.actor }}"
on:
  push:
    branches:
      - "master"

jobs:
  build_app:
    runs-on: "testing"
    container: "golang:1.19-bullseye"
    steps:
      - name: "Get repository..."
        uses: "actions/checkout@v3"

      - name: "Get dependencies..."
        run: "go mod tidy"

      - name: "Build application..."
        run: "go build -ldflags=\"-s -w\" -o ./output/app ./cmd/main.go"
