name: "Build application"
run-name: "${{ github.actor }}"
on:
  push:
    branches:
      - "master"

jobs:
  build_app:
    runs-on: "testing"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_LOGIN }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v3"
        with:
          context: "."
          push: true
          tags: "shadowuser17/testing:latest"
