name: "Build application"
run-name: "${{ github.actor }}"
on:
  push:
    branches:
      - "master"

jobs:
  build_app:
    runs-on: "k8s-runner"
    steps:
      - name: "Get repository..."
        uses: "actions/checkout@v3"

      - name: "Get golang..."
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19.X"
          cache: true

      - name: "Get dependencies..."
        run: "go mod tidy"

      - name: "Build application..."
        run: "go build -ldflags=\"-s -w\" -o ./output/app ./cmd/main.go"
        env:
           GOOS: "linux"
           GOARCH: "amd64"
